#!/usr/bin/env python3
"""Check both exports against the manuscript for missing, duplicated or reordered text.

Usage: python3 tools/book_build/verify.py books/<slug> [--release books/<slug>/release/v<version>]

Compares the manuscript's word sequence with (a) the DOCX body text and (b) the PDF body
text (running heads, page numbers and footnote-size text excluded). Words are normalised
(case, quotes, hyphens/dashes, line-end hyphenation) so only real content differences show.
Expected differences are listed separately:
  - placeholder lines removed by the build while book.json links are empty
  - footnote definitions (checked separately: all 9 present in each export)
  - list numbers typed in the source (DOCX/PDF generate them)
  - contents/index page numbers (PDF only)
"""
import argparse, difflib, glob, json, os, re, sys, zipfile

EXPECTED_REMOVED = ["leave a review on amazon", "instagram handle"]


def strip_markers(text):
    """Line-start list numbers ("1.", "**1.") are generated by DOCX/PDF: drop them on every side."""
    return "\n".join(re.sub(r"^[\s*_>\u2022-]*\d+\.(\s|$)", " ", l) for l in text.split("\n"))


def norm_words(text):
    text = strip_markers(text).replace("\u00ad", "")
    # letter-spaced small caps labels in the PDF ("C H A P T E R", "PA R T")
    text = re.sub(r"\b([A-Z]{1,2}(?:[ \u2009\u200a]+[A-Z]{1,2}){2,})\b", lambda m: re.sub(r"\s+", "", m.group(1)), text)
    text = re.sub(r"\b(CHAPTER|PART) (\d) (\d)\b", r"\1 \2\3", text)
    text = re.sub(r"(\w)-\s*\n\s*(\w)", r"\1\2", text)          # line-end hyphenation
    text = text.lower().replace("\u2019", "'").replace("\u2018", "'").replace("\u201c", '"').replace("\u201d", '"')
    words = []
    for w in text.split():
        w = re.sub(r"[^a-z0-9']", "", w).strip("'")
        if w:
            words.append(w)
    return words


def source_text(book_dir):
    out, notes = [], []
    for f in sorted(glob.glob(os.path.join(book_dir, "manuscript", "*.md"))):
        s = open(f, encoding="utf-8").read()
        for m in re.finditer(r"^\[\^[^\]]+\]:(.*(?:\n(?!\n).*)*)", s, re.M):
            notes.append(m.group(1))
        s = re.sub(r"^\[\^[^\]]+\]:.*(?:\n(?!\n).*)*", "", s, flags=re.M)   # footnote defs
        s = re.sub(r"\[\^[^\]]+\]", "", s)                                    # footnote refs
        s = re.sub(r"^\*\*\[Leave a review on Amazon\]\(REVIEW-LINK\)\*\*$", "", s, flags=re.M)
        s = re.sub(r"^- Instagram: \*\*@HANDLE\*\*$", "", s, flags=re.M)
        s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)
        s = re.sub(r"_{3,}", " ", s)                                          # write-in blanks
        out.append(s)
    return "\n".join(out), notes


def docx_text(path):
    import docx
    d = docx.Document(path)
    body = "\n".join(p.text for p in d.paragraphs)
    fn = zipfile.ZipFile(path).read("word/footnotes.xml").decode()
    notes = [re.sub(r"<[^>]+>", "", n) for n in re.findall(r'<w:footnote [^>]*w:id="[1-9]\d*".*?</w:footnote>', fn, re.S)]
    return re.sub(r"_{3,}", " ", body), notes


def pdf_text(path, cfg):
    import pymupdf
    d = pymupdf.open(path)
    H = d[0].rect.height
    top = cfg["print"]["margin_top_in"] * 72 - 2
    bottom = H - cfg["print"]["margin_bottom_in"] * 72 + 2
    lines, notes, front_list_pages = [], [], set()
    first_body = next(i for i, p in enumerate(d) if p.get_text().lstrip().startswith("Start Here") and "Contents" not in p.get_text())
    front_list_pages = set(range(2, first_body))           # index + contents pages (after title, copyright)
    for i, p in enumerate(d):
        for b in p.get_text("dict")["blocks"]:
            for l in b.get("lines", []):
                prev_x1 = None
                spans = [s for s in l["spans"] if s["text"].strip()]
                if not spans:
                    continue
                y0 = l["bbox"][1]
                if y0 < top or y0 > bottom:
                    continue                                   # running head / folio
                if max(s["size"] for s in spans) < 8.2:
                    notes.append(" ".join(s["text"] for s in spans)); continue   # footnotes (checked separately)
                body_spans = [s for s in spans if s["size"] >= 8.2]            # drop superscript note calls
                txt = ""
                for s_ in body_spans:
                    gap = txt and not txt.endswith(" ") and not s_["text"].startswith(" ")
                    txt += (" " if gap and prev_x1 is not None and s_["bbox"][0] - prev_x1 > 0.8 else "") + s_["text"]
                    prev_x1 = s_["bbox"][2]
                had_leader = bool(re.search(r"(\. ?){2,}", txt))
                txt = re.sub(r"(\. ?){2,}", " ", txt)            # leader dots
                txt = re.sub(r"^\s*•\s*", " ", txt)                  # generated bullets
                if i in front_list_pages:
                    if re.fullmatch(r"\s*\d{1,3}\s*", txt):
                        continue                                  # page number on its own line
                    txt = re.sub(r"(?<![\w.])[\s.]*\d{1,3}\s*$", " ", txt)  # trailing page reference
                lines.append(txt)
    body = "\n".join(lines)
    body = re.sub(r"\b(Chapters?|Part)\s*\n\s*(\d+)", r"\1 \2", body)   # number wrapped onto its own line
    body = re.sub(r"_{3,}", " ", body)
    return body, ["\n".join(notes)], d.page_count


def layout_checks(pdf_path, cfg):
    """Page refs vs real heading pages, links, margins, blank pages, stranded headings, split cards."""
    import pymupdf
    d = pymupdf.open(pdf_path)
    W, H = d[0].rect.width, d[0].rect.height
    pr = cfg["print"]; problems = []
    # 1. every printed contents/index page number = page where that heading really starts
    heads = {}
    for i, p in enumerate(d):
        for b in p.get_text("dict")["blocks"]:
            for l in b.get("lines", []):
                for sp in l["spans"]:
                    if sp["font"].startswith(("Book-Sans", "BookSans")) or "Sans" in sp["font"]:
                        if sp["size"] >= 12:
                            heads.setdefault(sp["text"].strip(), i + 1)
    import re as _re
    checked = 0
    for i in range(2, 8):
        for link in d[i].get_links():
            if link.get("kind") not in (pymupdf.LINK_GOTO, pymupdf.LINK_NAMED) or link.get("page", -1) < 0:
                continue
            target = link["page"] + 1
            words = d[i].get_text("words", clip=link["from"])
            nums = [w[4] for w in words if w[4].isdigit()]
            if nums and int(nums[-1]) != target:
                problems.append(f"page ref p{i+1}: prints {nums[-1]} but link goes to {target}")
            letters = lambda x: _re.sub(r"[^a-z]", "", x.lower())
            tp = letters(d[link["page"]].get_text())
            label = [w[4] for w in words if set(w[4]) != {"."}]
            if label[:1] and label[0] in ("Chapter", "Part"):
                label = label[2:]                                   # "Chapter 5:" is a separate label line
            label = [w for w in label if not w.isdigit() or len(label) < 2][:4]
            if label and letters(" ".join(label)) not in tp:
                problems.append(f"page ref p{i+1}: {' '.join(label)!r} not found on target page {target}")
            checked += 1
    print(f"   contents/index links checked: {checked}")
    # 2. margins: all body text inside the mirrored safe area
    for i, p in enumerate(d):
        right_page = (i + 1) % 2 == 1
        inside, outside = pr["margin_inside_in"] * 72, pr["margin_outside_in"] * 72
        left = inside if right_page else outside
        right = W - (outside if right_page else inside)
        for w in p.get_text("words"):
            x0, y0, x1, y1 = w[:4]
            if x0 < left - 1.5 or x1 > right + 1.5:
                if y0 > pr["margin_top_in"] * 72 - 2 and y1 < H - pr["margin_bottom_in"] * 72 + 2:
                    problems.append(f"p{i+1}: text outside margins: {w[4]!r} x={x0:.1f}-{x1:.1f}")
            if x0 < 0 or y0 < 0 or x1 > W or y1 > H:
                problems.append(f"p{i+1}: text off page: {w[4]!r}")
    # 3. blank pages
    blanks = [i + 1 for i, p in enumerate(d) if not p.get_text().strip()]
    if blanks:
        problems.append(f"blank pages: {blanks}")
    # 4. stranded headings: last body line on a page is a sans heading
    for i, p in enumerate(d):
        body = []
        for b in p.get_text("dict")["blocks"]:
            for l in b.get("lines", []):
                sp = [x for x in l["spans"] if x["text"].strip()]
                if sp and H - pr["margin_bottom_in"] * 72 > l["bbox"][1] > pr["margin_top_in"] * 72 and max(x["size"] for x in sp) >= 8.2:
                    body.append((l["bbox"][1], sp))
        if body:
            y, sp = max(body, key=lambda t: t[0])
            if i >= 2 and "Sans" in sp[0]["font"] and sp[0]["size"] >= 10.5 and i + 1 < len(d):
                problems.append(f"p{i+1}: page ends with heading {sp[0]['text']!r}")
    # 5. cards: title and last line on the same page
    import re as _re
    titles = ["POCKET CARD", "MELTDOWN TRACKER", "FILL-IN CARD", "OUR SAFE MAD LIST", "OUTING CHECKLIST",
              "OUR ROUTINE CHART", "SAY LESS CARD", "CALM-DOWN CORNER CHECKLIST", "REPAIR SCRIPT CARD",
              "CALM-DOWN PLAN"]
    for t in titles:
        pages = [i for i, p in enumerate(d) if t in p.get_text()]
        if not pages:
            problems.append(f"card missing: {t}"); continue
        p = d[pages[0]]
        rects = [dr["rect"] for dr in p.get_drawings() if dr.get("rect") and dr["rect"].width > 200 and dr["rect"].height > 40]
        if not rects:
            problems.append(f"card {t}: no box drawn on p{pages[0]+1}")
    print(f"   pages {len(d)}; size {W/72:.3f} x {H/72:.3f} in; blank pages {blanks or 'none'}")
    return problems


def compare(name, src_words, out_words):
    sm = difflib.SequenceMatcher(None, src_words, out_words, autojunk=False)
    problems = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        problems.append((tag, " ".join(src_words[i1:i2])[:120], " ".join(out_words[j1:j2])[:120]))
    ratio = sm.ratio()
    print(f"\n== {name}: {len(src_words)} source words vs {len(out_words)} output words, similarity {ratio:.5f}, "
          f"{len(problems)} difference(s)")
    for p in problems[:60]:
        print(f"   {p[0]:8} source: {p[1]!r}\n            output: {p[2]!r}")
    return problems


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("book_dir"); ap.add_argument("--release")
    a = ap.parse_args()
    cfg = json.load(open(os.path.join(a.book_dir, "book.json")))
    rel = a.release or os.path.join(a.book_dir, "release", "v" + cfg["version"])
    docx_path = glob.glob(os.path.join(rel, "*_Kindle.docx"))[0]
    pdf_path = glob.glob(os.path.join(rel, "*_Paperback-Interior_*.pdf"))[0]
    src, src_notes = source_text(a.book_dir)
    sw = norm_words(src)
    dt, dnotes = docx_text(docx_path)
    pt, pnotes, pages = pdf_text(pdf_path, cfg)
    p1 = compare("DOCX", sw, norm_words(dt))
    p2 = compare("PDF", sw, norm_words(pt))
    # footnotes: every source note's words must appear in each export's notes
    def notes_ok(out_notes):
        blob = " ".join(norm_words(" ".join(out_notes)))
        return [n.strip()[:60] for n in src_notes if " ".join(norm_words(n)) not in blob]
    print(f"\n== Footnotes: source {len(src_notes)} defs; DOCX notes {len(dnotes)}; missing in DOCX {notes_ok(dnotes)}; "
          f"missing in PDF {notes_ok(pnotes)}")
    print(f"== Expected removals (placeholders while book.json links are null): {EXPECTED_REMOVED}")
    print("\n== Layout checks (PDF)")
    p3 = layout_checks(pdf_path, cfg)
    for x in p3[:40]:
        print("   PROBLEM", x)
    print(f"   {len(p3)} layout problem(s)")
    sys.exit(1 if (p1 or p2 or p3) else 0)


if __name__ == "__main__":
    main()
